apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: "replace-me@example.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-route53
    solvers:
      - dns01:
          route53:
            region: "us-east-1"
            hostedZoneID: "Z1234567890ABC"
            accessKeyID: "REPLACE_ME"
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key
