apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-fsx
provisioner: smb.csi.k8s.io
parameters:
  source: "\\\\FSX_DNS_NAME\\share"
  csi.storage.k8s.io/node-stage-secret-name: smbcreds
  csi.storage.k8s.io/node-stage-secret-namespace: profisee
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
