apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profisee-fileshare
  namespace: profisee
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-fsx
  resources:
    requests:
      storage: 20Gi
